name = "AtomicArrays"
uuid = "47b95ec9-9f64-4e52-930c-0b1ac2f8934e"
authors = ["Alfredo Braunstein <alfredo.braunstein@polito.it> and contributors"]
version = "1.0.0"

[deps]
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
julia = "1.9"
Lazy = "0.15"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
